I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/1_chlorine.rpy", line 28, in script
    show cadence sad confused straight at portrait
  File "renpy/common/00layeredimage.rpy", line 775, in _choose_attributes
    raise Exception("The attributes for {} conflict: {}".format(tag, " ".join(both)))
Exception: The attributes for cadence conflict: straight confused

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/1_chlorine.rpy", line 28, in script
    show cadence sad confused straight at portrait
  File "E:\Renpy\renpy\ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "E:\Renpy\renpy\ast.py", line 1087, in show_imspec
    renpy.config.show(name,
  File "E:\Renpy\renpy\exports\displayexports.py", line 474, in show
    name, what = _find_image(layer, key, name, what)
  File "E:\Renpy\renpy\exports\displayexports.py", line 278, in _find_image
    new_image = renpy.game.context().images.apply_attributes(layer, key, name)
  File "E:\Renpy\renpy\display\image.py", line 990, in apply_attributes
    return self.choose_image(nametag, required, optional, name)
  File "E:\Renpy\renpy\display\image.py", line 1011, in choose_image
    newattrs = ca(tag, ca_required, ca_optional)
  File "renpy/common/00layeredimage.rpy", line 775, in _choose_attributes
    raise Exception("The attributes for {} conflict: {}".format(tag, " ".join(both)))
Exception: The attributes for cadence conflict: straight confused

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Lathe Cut Grooves 1.0
Thu Sep 25 00:20:00 2025
